### ISSUE TITLE
not an issue 

### ISSUE THREAD

**Issue by Bechebeche999** [anirudhmalik/xhunter#1]
POST HOW TO USE THIS BRAND NEW RAT 
Thank you <3

**Comment by anirudhmalik** [comment]
FEW FIXES AND UPDATES ARE PENDING. SOON WILL BE RELEASING APK **xhunter.apk** AND "How to use guide".
Main feature  includes 

1. ability to retrieve WhatsApp messages  
2. it use [localtunnel](https://www.npmjs.com/package/localtunnel) proxy to establish connection between attacker and victim [hack over the internet]
3. it also have binder feature to bind payload to other apps
4.etc...[all common Rat features]
