### ISSUE TITLE
Port issue

### ISSUE THREAD

**Issue by Attackndroid** [anirudhmalik/xhunter#11]
Do I have to change the IP in this client or will I work from the default? 
Because I'm having trouble opening the port, the panels are not opening, please wait forwarding port issues.

**Comment by anirudhmalik** [comment]
@Attackndroid I have used [localtunnel](https://github.com/localtunnel/localtunnel) library. Sometimes it is down. You can check here https://localtunnel.me if this link is reachable then you are good to go otherwise you will stuck on this screen

**Comment by Attackndroid** [comment]
But can't I use my own server so that it's not a problem, yes it's running very down.

**Comment by anirudhmalik** [comment]
@Attackndroid I will introduce that option in future update.I have already done the logic for that but ui is pending.
