### ISSUE TITLE
Port problem

### ISSUE THREAD

**Issue by EJ3CT** [anirudhmalik/xhunter#13]
can we use another mathod for port forwarding
example: portmap

**Comment by anirudhmalik** [comment]
@EJ3CT  Yes we can, but It does not provide **custom domain** and **custom port** in free version

**Comment by EJ3CT** [comment]
> @EJ3CT  Yes we can, but It does not provide **custom domain** and **custom port** in free version

i just wanna say can we use other free port forwarding service....localtunnel server is mostly down

**Comment by anirudhmalik** [comment]
@EJ3CT yes we can but i have not found any other service. I would love to know If you know any. remember it must provide:

> provide custom domain

>  and custom port

**Comment by Storm8lack** [comment]
@anirudhmalik  you could alternatively use https://localhost.run/ and it works the same way as localtunnel apart from custom subdomains.

**Comment by EJ3CT** [comment]
> @EJ3CT yes we can but i have not found any other service. I would love to know If you know any. remember it must provide:
> 
> > provide custom domain
> 
> >  and custom port 

sorry, currently i don't know about any other service

**Comment by EJ3CT** [comment]
> @EJ3CT yes we can but i have not found any other service. I would love to know If you know any. remember it must provide:
> 
> > provide custom domain
> 
> >  and custom port 

you can use http://www.localhost.run
