### ISSUE TITLE
Port Forwarding Issue

### ISSUE THREAD

**Issue by GrayMango77** [anirudhmalik/xhunter#14]
@anirudhmalik can you please explain when this option starts working again?
![Screenshot_2022-07-16-20-18-47-918_com xhunter](https://user-images.githubusercontent.com/109426488/179359899-877f5880-40d4-41dc-8a0d-107944878f0e.jpg)

**Comment by anirudhmalik** [comment]
@GrayMango77 I have used [localtunnel](https://github.com/localtunnel/localtunnel) library. Sometimes it is down. You can check here https://localtunnel.me/ if this link is reachable then you are good to go otherwise you will stuck on this screen.
It usually comes back live in few hours
