### ISSUE TITLE
ApkBuilder Bind+Build error

### ISSUE THREAD

**Issue by HeatWavve** [anirudhmalik/xhunter#29]
You have created best app. Great Job. loved you dedication towards this project!!!

**Issues i am facing:**
1. Connection will end once you close app from recent.
2. In bind+payload i have binded many apps but apps are crashing while installing. Can you please suggest any app for binding rather than gbwhatsapp.

**Features to add:**
1. Can you please add location tracking feature.
2. Can you add only payload creation option separately without binding with any app.
3.  Can you make payload persistent.

**Comment by anirudhmalik** [comment]
@HeatWavve 
- l have tried persistent, It only works below `android 9`.
- If we need to make it persistent about `android 10` then we need to show notification to make it work.
- therefore I have provided binding method. so we can bind payload to the app that is used frequently by user.

Can you send me link to those app you tried binding.so I can run debug issue.

Features will be available in upcoming updates.

**Comment by HeatWavve** [comment]
@anirudhmalik 

i have tried with Flappy Bird 1.3.apk and facebook lite.apk

**Comment by Storm8lack** [comment]
I get the same error with the new update, I tried several applications.

https://user-images.githubusercontent.com/108852442/180164700-28b2ce9c-925c-4465-8dcf-bfcb982d1c01.mp4

**Comment by anirudhmalik** [comment]
@HeatWavve flappy bird apk is outdated.
Facebook lite and few apps can't be build.
You can try on other apps

**Comment by HeatWavve** [comment]
@anirudhmalik

Xhunter app crashing while binding any APK. Facing same issue which @Storm8lack provided above.

**Comment by Storm8lack** [comment]
> @anirudhmalik
> 
> La aplicación Xhunter falla al vincular cualquier APK. Enfrentando el mismo problema que@Storm8lackproporcionado anteriormente.

Exactly it keeps crashing the application does not finish the compilation process.  I tried several apps and they have the same error.

**Comment by anirudhmalik** [comment]
@Storm8lack   I have found the bug, It is was decoding payload apk for both payload and normal apk,

**Comment by SarkonTampan** [comment]
Has this been fixed?, if so, why is there no update in the application?

**Comment by anirudhmalik** [comment]
> Has this been fixed?, if so, why is there no update in the application?

It's already fixed I have updated the release

**Comment by hunte1r** [comment]
i am still have same problem i cant build payload from any apk its all failed

**Comment by hunte1r** [comment]
> > Has this been fixed?, if so, why is there no update in the application?
> 
> It's already fixed I have updated the release

.
i am still have same problem i cant build payload from any apk its all failed

**Comment by Ryc882** [comment]
Bro when i trying to build paylod both its stopped automatically
