### ISSUE TITLE
Payload error

### ISSUE THREAD

**Issue by SarkonTampan** [anirudhmalik/xhunter#32]
Payload error
![Screenshot_2022-07-22-11-08-46-448_com gbwhatsapp](https://user-images.githubusercontent.com/108641435/180360712-3e6b8089-55e0-40b0-aeb8-5a4ce5563753.jpg)

**Comment by anirudhmalik** [comment]
@SarkonTampan what exactly have you requested from xhunter app. like read sms, send sms, contact....etc when this happened on payload.

**Comment by anirudhmalik** [comment]
@SarkonTampan there is no option for camera.

**Comment by anirudhmalik** [comment]
It is due to android permission not allowed by victim.
and after some debugging I found out a tiny bug that will be patched.
#activity_compact

**Comment by Raja998877** [comment]
Hunter Sir Please Update GBwhatsapp Because I Install then Show Out Of Date Please Fix
