### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Anonymous19001** [anirudhmalik/xhunter#34]
Can xhunter rat be run on android version 6 not payload?

**Comment by anirudhmalik** [comment]
It works fine above android 8. you may face signing payload error

**Comment by Anonymous19001** [comment]
Yes when i click on build payloads and give my herokuapp server link and it starts building but when it comes to ziping resourses app crashed any solution?

**Comment by anirudhmalik** [comment]
Try on other device or wait for next update I will make it compatible.
