### ISSUE TITLE
Python server

### ISSUE THREAD

**Issue by Ruben978** [anirudhmalik/xhunter#39]
Just a little question if I want to make server in python how to do that?

**Comment by sunpx3** [comment]
> Just a little question if I want to make server in python how to do that?
> 
> import socket s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) s.bind(("name.herokuapp.com", 443)) s.listen(5) c, addr = s.accept()

=============a simple cod [example]============
`# coding: utf-8
import sys

import socketio
import eventlet.wsgi

# 创建sio 对象
sio = socketio.Server(cors_allowed_origins="*", asyne_model="eventlet")
app = socketio.Middleware(sio)

ip = "192.168.113.102"
port = 7777

# sockio 服务器的运行地址
SERVER_ADDRESS = (ip, port)

# 用携程启动服务
socket = eventlet.listen(SERVER_ADDRESS)

@sio.event
def connect(sid, environ):
    print('connect ', sid)

@sio.event
def my_message(sid, data):
    print('message ', data)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(socket, app)`

**Comment by Ruben978** [comment]
> > Just a little question if I want to make server in python how to do that?
> > import socket s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) s.bind(("name.herokuapp.com", 443)) s.listen(5) c, addr = s.accept()
> 
> =============a simple code [example]============ `# coding: utf-8 import sys
> 
> import socketio import eventlet.wsgi
> 
> sio = socketio.Server(cors_allowed_origins="*", asyne_model="eventlet") app = socketio.Middleware(sio)
> 
> ip = "192.168.113.102" port = 7777
> 
> SERVER_ADDRESS = (ip, port)
> 
> socket = eventlet.listen(SERVER_ADDRESS)
> 
> @sio.event def connect(sid, environ): print('connect ', sid)
> 
> @sio.event def my_message(sid, data): print('message ', data)
> 
> @sio.event def disconnect(sid): print('disconnect ', sid)
> 
> if **name** == '**main**': eventlet.wsgi.server(socket, app)`

Much appreciation

**Comment by Ruben978** [comment]
> > Just a little question if I want to make server in python how to do that?
> > import socket s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) s.bind(("name.herokuapp.com", 443)) s.listen(5) c, addr = s.accept()
> 
> =============a simple code [example]============ `# coding: utf-8 import sys
> 
> import socketio import eventlet.wsgi
> 
> sio = socketio.Server(cors_allowed_origins="*", asyne_model="eventlet") app = socketio.Middleware(sio)
> 
> ip = "192.168.113.102" port = 7777
> 
> SERVER_ADDRESS = (ip, port)
> 
> socket = eventlet.listen(SERVER_ADDRESS)
> 
> @sio.event def connect(sid, environ): print('connect ', sid)
> 
> @sio.event def my_message(sid, data): print('message ', data)
> 
> @sio.event def disconnect(sid): print('disconnect ', sid)
> 
> if **name** == '**main**': eventlet.wsgi.server(socket, app)`

Tried but not working :(
