### ISSUE TITLE
Payload not BUILDING 

### ISSUE THREAD

**Issue by scuminer** [anirudhmalik/xhunter#4]
Everytime I try to build the payload it says following, also tried to install multiple time but still same
![Screenshot_2022-07-07-01-13-18-807_com xhunter](https://user-images.githubusercontent.com/103521348/177630594-2ebbc7a7-70ba-4642-80b8-3c6969f7c6e3.jpg)

**Comment by anirudhmalik** [comment]
Can you create folder `XHUNTER` in your internal storage manually and then inside it `payload` and then try again.
Also check for the file storage read write permission

![IMG_20220707_082838](https://user-images.githubusercontent.com/70255938/177681272-fee125fd-dbaa-4b98-a96a-3e685f9a5191.jpg)
![IMG_20220707_082856](https://user-images.githubusercontent.com/70255938/177681302-2bc976ef-477c-4ba4-b463-3eeeb5077b0a.jpg)

**Comment by scuminer** [comment]
Tried everything, checked all the permissions there're all correct, also manually made all folders but now when I try to buil the apk the app automatically closes

**Comment by anirudhmalik** [comment]
@scuminer I have found out the issue. `android 11+` devices are facing it soon I will patch it.

**Comment by anirudhmalik** [comment]
> Still has the same issue, even after you patched it
Please check now, I forgot to change `targetSdkVersion = 28` earlier it was 30
