### ISSUE TITLE
problem in Building payload

### ISSUE THREAD

**Issue by hunte1r** [anirudhmalik/xhunter#43]
99% of the apps I'm trying to combine with payload it fail I hope for you fix this problem And there is a bigger problem, which is that the connection is lost when the victim exits the application

-i am week in English

**Comment by Storm8lack** [comment]
> 

the error is due to the applications having a high level of obfuscation.  download the applications from this link it has worked for me https://apkmody.io/

**Comment by Storm8lack** [comment]
> El 99% de las aplicaciones que intento combinar con la carga útil fallan. Espero que solucionen este problema. Y hay un problema mayor, que es que la conexión se pierde cuando la víctima sale de la aplicación.
> 
> -soy semana en ingles

the error is due to applications having a high level of obfuscation. download the apps from this link it worked for me on payload injection. https://apkmody.io/

**Comment by hunte1r** [comment]
> > El 99٪ de las aplicaciones que intento combinar con la carga útil valan. Espero que solucionen este problema. Y hay un problema mayor، que es que la conexión se pierde cuando la víctima sale de la aplicación.
> > -صوي سيمانا إنجلز
> 
> يرجع الخطأ إلى التطبيقات التي تحتوي على مستوى عالٍ من التشويش. قم بتنزيل التطبيقات من هذا الرابط ، فقد عملت معي على حقن الحمولة. https://apkmody.io/

it all app in this link will working?

**Comment by HackerAakashAK** [comment]
Sir Please Write A Discription For How To Update GBwhatsapp Because When I Make GBwhatsapp Then It Out Of Date 😥

**Comment by Smartmedia555** [comment]
The app keep failing my Payload
