### ISSUE TITLE
Crashing Project on Windows

### ISSUE THREAD

**Issue by Ruben978** [anirudhmalik/xhunter#45]
I am trying to run from source code but it's always crashing after splash screen can I ask you which version of java and react-native you are running?

**Comment by anirudhmalik** [comment]
This project will not run windows instead use mac. 
reason : I have used [node-js-mobile-react-native](https://www.npmjs.com/package/nodejs-mobile-react-native) which crashes after first build. I don't know why it happens but the root cause is this library.

**Comment by Ruben978** [comment]
> This project will not run windows instead use mac. reason : I have used [node-js-mobile-react-native](https://www.npmjs.com/package/nodejs-mobile-react-native) which crashes after first build. I don't know why it happens but the root cause is this library.

I don't have Mac can I use Linux instead?

**Comment by anirudhmalik** [comment]
@Ruben978 Yes, It could run on linux but I have never tried on Linux
