### ISSUE TITLE
Keeps Loading and Gps Location error

### ISSUE THREAD

**Issue by Storm8lack** [anirudhmalik/xhunter#46]
The application so far has grown a lot, but it has errors to be corrected, according to the tests I have carried out:

  •When you enter the victim's options, it recognizes your data well, but it doesn't allow you to download anything, or view any image or file.

  •When browsing the victim's options it loads the data, but when you go back to the main menu and re-enter to view the files it doesn't load the data.

  •When the victim exits the application they are disconnected.

  •Does not recognize GPS location

https://user-images.githubusercontent.com/108852442/180662390-c362ae42-7252-4300-89e8-46ac39b5afae.mp4

Congratulaciones for your great effort

**Comment by anirudhmalik** [comment]
## please update your [xhunter-server](https://github.com/anirudhmalik/xhunter-server) on heroku

- it will fix loading issue
- gps location 

root cause : fixed preview image option which caused server to crash. therefore it keeps loading forever
see changes [here](https://github.com/anirudhmalik/xhunter-server/commit/895ea5f9469366efeb419ec8eac64c5d343af3ae)

**Comment by Storm8lack** [comment]
> 

How to update the x hunter-server on heroku?

> ## actualiza tu [servidor](https://github.com/anirudhmalik/xhunter-server) xhunter en heroku
> * solucionará el problema de carga
> * ubicación gps
> 
> causa raíz: opción de imagen de vista previa fija que causó que el servidor fallara. por lo tanto sigue cargando para siempre ver cambios [aquí](https://github.com/anirudhmalik/xhunter-server/commit/895ea5f9469366efeb419ec8eac64c5d343af3ae)

How to update the x hunter-server on heroku?

**Comment by anirudhmalik** [comment]
@Storm8lack Delete the heroku app from heroku dashboard.
And then again deploy xhunter-server by deploy button.
ps: you can use the same `<app_name>` again there will be no issue.

**Comment by Storm8lack** [comment]
With the update of the heroku server I improve the data transmission and the GPS. but still the victim error persists when the app closes it gets disconnected, also the install error when it finishes compiling the app. another bug is that the GPS only works with the app open.

https://user-images.githubusercontent.com/108852442/180675071-3a6b9771-452f-4b00-9e95-efdc97dbc680.mp4

**Comment by anirudhmalik** [comment]
It is under testing #49
