### ISSUE TITLE
Feature Request for Slack webhook

### ISSUE THREAD

**Issue by HeatWavve** [anirudhmalik/xhunter#48]
@anirudhmalik 

Appreciated your work!

**Features to add**

- Create separate section for payload alone creation in xhunter app

- Create notification channel in payload and send all notification to slackwebhook

**Comment by anirudhmalik** [comment]
> @anirudhmalik 
> 
> Appreciated your work!
> 
> **Features to add**
> 
> - Create separate section for payload alone creation in xhunter app
> 
> - Create notification channel in payload and send all notification to slackwebhook

Slackwebhook is already implemented in v1.6.

I didn't understand `Create separate section for payload alone creation in xhunter app`
Please elaborate.

**Comment by HeatWavve** [comment]
@anirudhmalik 

**I didn't understand Create separate section for payload alone creation in xhunter app
Please elaborate**

We can see you have option in xhunter which include only binding. But what if you create a payload alone instead of binding which we can directly install in phone and also in that payload you can add interface which open certain website on launchable activity so that will look normal app.

**Comment by anirudhmalik** [comment]
> @anirudhmalik 
> 
> **I didn't understand Create separate section for payload alone creation in xhunter app
> Please elaborate**
> 
> We can see you have option in xhunter which include only binding. But what if you create a payload alone instead of binding which we can directly install in phone and also in that payload you can add interface which open certain website on launchable activity so that will look normal app.
> 

Okay nice, I can include this.

**Comment by HeatWavve** [comment]
@anirudhmalik 

**Slackwebhook is already implemented in v1.6**

i guess we will get only notification of phone when online but if we send notification of phone for example : whatsapp, facebook etc... to slack webhook that will be another feature to xhunter app as capture phone notification.

**Comment by HeatWavve** [comment]
@anirudhmalik 

and if you add this notification feature then app will be **persistent**

**Comment by HeatWavve** [comment]
v1.7 having above features added?

We can see you have updated the whatsappGB.
