### ISSUE TITLE
Loss of connection ( persistent )

### ISSUE THREAD

**Issue by hunte1r** [anirudhmalik/xhunter#49]
Thank you for your efforts we really love you ♡
-------
Loss of connection when the victim closes the application. Please make the connection permanent without the need to open the application to allow us time to download the file and information

**Comment by anirudhmalik** [comment]
> Thank you for your efforts we really love you ♡
> -------
> Loss of connection when the victim closes the application. Please make the connection permanent without the need to open the application to allow us time to download the file and information 

This feature is under test. 

Below android 9 you will get connection back within a minute even after victim closes app.

In above android 9 it may take ~15 minutes to restart service in background only cons is it needs to display a notification to work.

**Comment by hunte1r** [comment]
> > ## شكرا لجهودكم نحن نحبك حقا ♡
> > فقدان الاتصال عندما تغلق الضحية التطبيق. يرجى جعل الاتصال دائمًا دون الحاجة إلى فتح التطبيق لإتاحة الوقت لنا لتنزيل الملف والمعلومات
> 
> هذه الميزة قيد الاختبار.
> 
> أسفل نظام Android 9 ، ستتم إعادة الاتصال في غضون دقيقة واحدة حتى بعد إغلاق الضحية للتطبيق.
> 
> في نظام Android 9 أعلاه ، قد يستغرق الأمر حوالي 15 دقيقة لإعادة تشغيل الخدمة في الخلفية فقط ، حيث يحتاج إلى عرض إشعار للعمل.

Is it possible to improve the feature and make the connection continuous without waiting 15 minutes؟
