### ISSUE TITLE
This RAT is Very Good for Android 

### ISSUE THREAD

**Issue by Pikaos** [anirudhmalik/xhunter#57]
This RAT is very Good RAT ❤️❤️❤️💕🔥🥰🌟💘
Thanks For working on this RAT may God Bless You

**Comment by sunpx3** [comment]
> This RAT is very Good RAT hearthearthearttwo_heartsfiresmiling_face_with_three_heartsstar2cupid Thanks For working on this RAT may God Bless You
haha , I have successfully attacked with rat

**Comment by E0777** [comment]
But, it need to be updated as GBWhatsapp get new update !
