### ISSUE TITLE
no options for herokuapp or other servers

### ISSUE THREAD

**Issue by akh33l** [anirudhmalik/xhunter#59]
**Describe the bug**

**To Reproduce**

hello
after install apk and start build payload

the option for enter herokuapp not found
and also for other servers
 when i start build payload its continue without the option of choosing

if there a way to solve that

**Comment by anirudhmalik** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> hello
> after install apk and start build payload
> 
> the option for enter herokuapp not found
> and also for other servers
>  when i start build payload its continue without the option of choosing
> 
> if there a way to solve that

Please update your app to v1.6
