### ISSUE TITLE
aid!!! [assets folder issue]

### ISSUE THREAD

**Issue by Storm8lack** [anirudhmalik/xhunter#6]
the RAT has an error using the build+bind payload... even when installing v1.1

https://user-images.githubusercontent.com/108852442/177863163-0cd9b0e0-7c4d-430a-968c-59ae53d26eef.mp4

**Comment by Storm8lack** [comment]
compiled the RAT with android 11 and 9 it didn't work

**Comment by anirudhmalik** [comment]
@Storm8lack there was an issue `assets folder not found` I have fixed it. and will release soon.
