### ISSUE TITLE
 Permission fix

### ISSUE THREAD

**Issue by uglykid69** [anirudhmalik/xhunter#60]
Hey im testing xhunter pretty comprehensively and i have come to a fix.

Bug.
Whenever i bind payload to an app and inject payload permission into it. It simply doesnt asks for "PAYLOAD" permissions after that app is installed.

Fix.
The fix for it is very simple just change minsdkverison to 10 & maxsdkversion to 17 and the problem gets solved.

**Comment by IgSkDevil** [comment]
Ok tq✨💝
