### ISSUE TITLE
Multiple file selection download feature and SMS,CALLOG, CONTACTS DUMP feature

### ISSUE THREAD

**Issue by uglykid69** [anirudhmalik/xhunter#67]
Hey dev, Hru? Hope you are having a  wonderful day.

-I really like the file manager in xhunter.

But there is that 1 tiny feature that is missing "Multiple Selection"

-Why this feature?

Sometimes we don't have so much time to check the files and download after. So selection can greatly help to download all files in one go.

-SMS DUMP,CALLLOG DUMP, CONTACTS DUMP.

-why this feature?

Sometimes victim only comes only for few couple of seconds and screen recording every section is really pain in the as*.

PS: I really appreciate your hard work and im not forcing you to add these feature. I just really really like your concept of xhunter and i want to see it as perfect as possible. Hope you keep up the good work.

**Comment by SmartSmart3** [comment]
👍
