### ISSUE TITLE
Request urgent

### ISSUE THREAD

**Issue by murtaza9292** [anirudhmalik/xhunter#80]
Respected sir,
Please guide me to remove the payload from the gbwhatsapp. Because i am in trouble due to some reason. I am not able to reverse the action and this shows a warning messages again and again while texting. Also voice is not working. Please help me.

**Comment by anirudh-antino** [comment]
@murtaza9292 Install this latest version it will automatically remove infected one.
https://down.gbapps.net/GBWhatsApp_Updated.apk

**Comment by murtaza9292** [comment]
Thank you i will try
