### ISSUE TITLE
Dear sir 

### ISSUE THREAD

**Issue by SmartSmart3** [anirudhmalik/xhunter#89]
I would like to put the payload

**Comment by lulavc** [comment]
Hello. I need someone good on removíng some obfuscstion and bypass some
hwid Lock on a program(ilegal) one

Willing to pay about 400 usd for doing on 3 programs.

Em dom., 14 de ago. de 2022 05:17, SmartSmart3 ***@***.***>
escreveu:

**Comment by HeatWavve** [comment]
@SmartSmart3  build payload alone from xhunter repo from android studio or AIDE and edit assets/ip.txt with your ip and slackwebhook url

**Comment by HeatWavve** [comment]
@SmartSmart3 You can install that payload after building then you will get connection in xhunter without binding with any apk
